parameters:
  - name: platformWorkloadSettings
    type: object

stages:
  - template: /common/pipelines/01-orchestrators/alz.devops.workload.orchestrator.yml@release-engine-core
    parameters:
      workloadSettings:
        name: oci_artifact_capability
        configurationFilePath: ${{ parameters.platformWorkloadSettings.configurationFilePath }}
        environments: ${{ parameters.platformWorkloadSettings.environments }}
        workloadArtifactsPath: /patterns/oci_artifact_capability
        stages:
          # It is possible to create stages dynamically, defined at configuration level, currently used for Subscription Vending
          # - ${{ each collectionItem in parameters.platformWorkloadSettings.collection }}:
          - infrastructure:
              iac:
                name: oci_artifact_capability
                deploymentScope: Subscription
                serviceConnection: $(serviceConnection)
                iacMainFileName: workload.bicep
                iacParameterFileName: ${{ parameters.platformWorkloadSettings.iacParameterFileName }}